### ISSUE TITLE
Examples for the Haskell compability

### ISSUE THREAD

**Issue by ShalokShalom** [gusty/FSharpPlus#66] opened 2018-01-08 10:06 UTC
Currently, there is no example in the tutorial for the compatibility with Haskell.

**Comment by wallymathieu** [comment] 2018-01-08 11:13
There are the following samples:
- [Haskell.fsx](https://github.com/gusty/FSharpPlus/blob/master/src/FSharpPlus/Samples/Haskell.fsx)
- [Learn You a Haskell.fsx](https://github.com/gusty/FSharpPlus/blob/master/src/FSharpPlus/Samples/Learn%20You%20a%20Haskell.fsx)

**Comment by wallymathieu** [comment] 2018-01-08 11:13
So perhaps having links to these files would help?

**Comment by ShalokShalom** [comment] 2018-01-08 11:15
Copy and paste the content, IMHO.

**Comment by gusty** [comment] 2018-01-08 19:27
By pure causality, yesterday I almost copy the sample files to the docs for the Haskell Compatibility. In the end I decided that I would want to review the code and that will take me some time (which yesterday I didn't had). So let's discuss a bit how to organize this samples in the docs.

As I said yesterday in another discussion, I see an overlap between the samples and the docs, since the docs also contain sample and my guess is that we should move all the samples to the doc. Again this is not just copy-paste, it will require adding some explanations to the sample code.

**Comment by ShalokShalom** [comment] 2018-01-08 22:18
By pure causality, I almost suggested to actually copy the sample files and was then concerned that this is too much code for this overview. IMHO, a more generic and simple example is suitable.

**Comment by wallymathieu** [comment] 2018-01-09 05:11
Operation | F#+ / F# | Haskell
-- | -- | --
List.append | @ | ++
  | << | .
  | <\| | $
  | = | ==
  | <> | =/
flip | /> | />
apply function to value | </  or  \|> | </
  |   |  
Functor |   |  
map | <!> or <<\| | <$> or fmap
same as map but arguments interchanged | \|>> |  
  |   |  
Monoid |   |  
monoid zero element | getZero() | mempty
append | ++ or plus | mappend
  |   |  
Applicative functors |   |  
apply (combine) | <*> | <*>
Sequence actions, discarding the value of the first argument. | *> | *>
Sequence actions, discarding the value of the second argument. | <* | <*
A variant of <*> with the arguments reversed. | <**> | <**>
Lift a value. | result | pure
  |   |  
Alternative |   |  
alternatives: binary operation | <\|> | <\|>
  |   |  
Monad |   |  
Bind Sequentially compose two actions, passing any value produced by the first as an argument to the second. | >>= | >>=
Same as >>=, but with the arguments interchanged. | =<< | =<<

**Comment by wallymathieu** [comment] 2018-01-09 05:11
?

**Comment by wallymathieu** [comment] 2018-01-09 05:14
And then add a column?

**Comment by wallymathieu** [comment] 2018-01-09 05:20
Then we could perhaps write what can and cannot be done in f# compared to Haskell

**Comment by gusty** [comment] 2018-01-09 06:17
@wallymathieu @ShalokShalom feel free to send a PR regarding this, whoever takes the initiative (including myself) just send a message first to avoid duplicate efforts.

My feeling is that we should add that table and regarding the sample files there are actually two files. One is too short, the other one is too long.

The long one, is in the Samples From FsControl folder, which at the same time came from an old exploratory project, originally in google code but now it's being imported to github by some devs, [see this import]( https://github.com/flarelee/fsharp-typeclasses/blob/master/Script.fsx) and also this other import, with the [translation table used at that time](https://github.com/SteveGilham/fsharp-typeclasses/commit/8b090e6d07086b1bb857df9ba63d2cea53753863).

Now regarding the Learn you a Haskell file, that was an exercise @vstastny did to learn about the typeclassy stuff here, following the original haskell tutorial, and he gently contributed back to this repo. But note that it's not using the Haskell compatibility, because the idea I think, was to apply the same concepts in F#. So I think it worths adding to the doc, but maybe not in the compatibility (although it might be linked). One thing is syntax and another is abstractions.

**Comment by ShalokShalom** [comment] 2018-01-09 08:27
I absolutely adore this table.

**Comment by wallymathieu** [comment] 2018-01-09 08:32
The easiest way to get the table into the docs could be to use github wiki ? Then we could start collaborate on it as well.

**Comment by wallymathieu** [comment] 2018-01-09 08:33
Since it does not contain any code examples, it's perhaps not so much a good fit for literate style of programming with fsx, or what's your thougts @gusty ?

**Comment by gusty** [comment] 2018-01-09 08:51
> The easiest way to get the table into the docs could be to use github wiki ?

I don't get it, what's complicated? You can put it directly in the docs, they support markdown directly AFAIK.

**Comment by wallymathieu** [comment] 2018-01-09 08:52
It doesn't support the same markdown syntax. It's a minor thing: you need to transform it into a table that the dialect of markdown that fsharp formatting supports.

**Comment by gusty** [comment] 2018-01-09 08:55
Shame, but moving that out of the docs for a technical limitation seems hacky,
Is there any other way? Something like linking to an external site, as I did for the PlantUML diagram?

**Comment by gusty** [comment] 2018-01-09 08:56
>  It's a minor thing: you need to transform the table to the dialect of markdown that fsharp formatting supports.

Actually this might be the easiest solution. What do you think?

**Comment by wallymathieu** [comment] 2018-01-09 08:56
Indeed.

**Comment by wallymathieu** [comment] 2018-01-09 09:05
The question is mostly what kind of markdown tables fsharp formatting supports?

**Comment by gusty** [comment] 2018-01-09 09:18
https://github.com/fsprojects/FSharp.Formatting/issues/7 and see the linked examples.

**Comment by wallymathieu** [comment] 2018-01-09 09:19
Nice!

**Comment by ShalokShalom** [comment] 2018-01-10 14:42
Very nice to see, that something trivial gets immediately implemented, while the whole range of the .NET world is still in chaos: https://github.com/dotnet/docs/issues/3446

**Comment by wallymathieu** [comment] 2018-01-11 08:57
https://gist.github.com/wallymathieu/19c74f784652f18ae3111056b8403f82

**Comment by wallymathieu** [comment] 2018-01-11 08:58
So perhaps someone wants to do a small pull request :wink:

**Comment by gusty** [comment] 2018-01-11 09:13
Cool !
I found some inaccuracies, here's the [corrected version](https://gist.github.com/gusty/6614cb2fb779aafcfe59678c8ac3e590)

Also I noticed some issues.

 - Why don't we use ``(/=)`` directly? I don't remember if there was an issue, it was many years ago, maybe the F# parser at that time rejected it.

 - ``(++)`` should be redefined in the Haskell compatibility. I probably forgot to add it.

**Comment by ShalokShalom** [comment] 2018-01-11 11:08
OK, i did some changes to this, lets see how they appeal you: 

https://gist.github.com/ShalokShalom/11cf9b1943d36ac51939e83bb0fced84

**Comment by ShalokShalom** [comment] 2018-01-11 11:18
Some question: 

- [$ seems to have another function as <|](https://stackoverflow.com/questions/940382/haskell-difference-between-dot-and-dollar-sign)

- I suggest creating an issue for each operator, which is still unported. 
  We can then link to this specific issue from that comparison table.

- Some operators still seem to be unnamed yet: What is the purpose behind?

**Comment by wallymathieu** [comment] 2018-01-11 12:14
I've started using `<|` sort of the same way I use it in Haskell. Since I'm not very deep into it, it's kind of helpful to have something where it's explained.

**Comment by gusty** [comment] 2018-01-11 17:15
Not all operators are representable in F#, we can create issues, but the right place to create them will be in the F# compiler project, because there's nothing we can do about it here.

Regarding ``$`` it's a bit for completeness there, but actually the main purpose of the operator which is to avoid parens, it's defeated since it doesn't have the same associativity as in Haskell. Again, there's nothing we can do about it.

> Some operators still seem to be unnamed yet: What is the purpose?

Which one, for example?

> I've started using <| sort of the s ...

Yes, I use it from time to time, but it also has not the same associativity, so for piping expressions it doesn't work, it's better to do the F# way, I mean reverse the pipe and write with the ``|>`` in those cases.

**Comment by wallymathieu** [comment] 2018-01-11 17:26
Mmm, indeed. What is your thoughts about the Ocaml way of doing things? More module oriented instead of type class oriented.

**Comment by gusty** [comment] 2018-01-11 18:33
I don't have any experience in OCaml, but it seems to be more module oriented.
AFAIK they use their "functor" feature, which is not the same as the functor abstraction, it's rather a parametrizable module and they don't have typeclasses, but I read somewhere that both techniques are equivalent.

**Comment by ShalokShalom** [comment] 2018-01-12 09:09
OCaml is very module oriented since they allow higher-order polymorphism / higher order modules. 

Ah, I got now that I can use <| in order to substitute the $ in Standard F-Sharp.

> Which one, for example?

Well, in my perspective, the whole left column could be filled with text. 

`=`, `<|` and `<>` are without such one yet and `apply function to a value ` is without operators.

If there are no equivalents on one side or the other, we can mention that with something like `not available`

Otherwise, this list looks incomplete, respectively its not clear if the list is incomplete or the operator is missing.

**Comment by wallymathieu** [comment] 2018-01-12 09:40
https://github.com/gusty/FSharpPlus/blob/master/src/FSharpPlus/Compatibility.fs#L94

**Comment by ShalokShalom** [comment] 2018-01-12 09:41
Oh, then Github`s search does probably crash with `

Thanks a lot

**Comment by wallymathieu** [comment] 2018-01-12 09:56
apply function to a value `</ or |>` has gotten dropped

**Comment by ShalokShalom** [comment] 2018-01-12 09:58
So we can remove it?

**Comment by ShalokShalom** [comment] 2018-01-12 09:58
Or mention `not available`

**Comment by wallymathieu** [comment] 2018-01-12 10:04
It's very common in f# code, so if it's not available in Haskell then I would find it useful have that fact in the table.

**Comment by wallymathieu** [comment] 2018-01-12 11:15
I don't remember why I added </ for Haskell.

**Comment by ShalokShalom** [comment] 2018-01-12 11:44
I meant at all. 

See now: https://gist.github.com/ShalokShalom/11cf9b1943d36ac51939e83bb0fced84

So, how can I see the specific result of this table?

How does it look like in real life?

Since I like to start adjusting the visually appealing. 

I hope its fine, that I actually name this project specifically?

F#+ Haskell Compatibility burst the width of the column, so I think this can make it leaner and also give the project some identity. :)

**Comment by gusty** [comment] 2018-01-12 11:44
> apply function to a value </ or |> has gotten dropped

Yes, the definitions are 3 rows above.

> And if binary operation is available in both F-Sharp and Haskell, why implement one in F-Sharp Plus?

Do they work differently?
Not 100% sure what do you mean. 
Regarding to ``<|>`` it's simply the same operator in Haskell and FSharpPlus and also in other languages, like purescript, Idris if I'm not wrong.

> I don't remember why I added </ for Haskell.

That's confusing, probably it was added by me in the original project. The thing is that in Haskell you can partially apply an operator on both sides, well I found out that by using those operators you achieve more or less the same effect but at the cost of ending up with combination of operators. Here's an example:

    let f x = fun n -> n - x

in Haksell you can write it:

    let f x = (- x)

here you can write:

    let f x = (-)/> x

But in fact the idea of these operators is to be able to transform a function in an operator: 

    let sum x y = x + y

    let a = x </sum/> y

**Comment by ShalokShalom** [comment] 2018-01-12 11:47
Oh, I see. I thought initially, this table is just to point out the compatibility layer itself. 
So, in that case, a huge load of operators is missing?

**Comment by ShalokShalom** [comment] 2018-01-12 11:47
What should get included and what not?

**Comment by ShalokShalom** [comment] 2018-01-12 11:51
> But in fact the idea of these operators is to be able to transform a function in an operator:

```
let sum x y = x + y

let a = x </sum/> y

```
I think we should point this out on its own. Otherwise, the whole sense would get gone.

**Comment by gusty** [comment] 2018-01-12 11:52
Definitely.

**Comment by gusty** [comment] 2018-01-12 11:52
> What should get included and what not?

I would say, let's get it done with the basic stuff, as we have it for example.
The goal of the Haskell compatibility module is to facilitate translating code from Haskell, including running on-off examples, but normally if you translate something that later will become more important we should remove the Haskell compatibility. A good example os this, is the recent @wallymathieu work with Validations, see for example that inflexion point [happening here](https://github.com/wallymathieu/FSharpPlus.Validations/commit/e3685689fbc719071b63cfc443d726880059f48d)

**Comment by ShalokShalom** [comment] 2018-01-12 11:55
> we should remove the Haskell compatibility

So, a Haskell compatibility source-to-source converter onto F-Sharp would be reasonable?

To do this automaticly?

**Comment by gusty** [comment] 2018-01-12 12:02
It will never be possible to fully emulate Haskell, specially because of the lazyness and the different type system. Still, my experience is that Haskell.Compatibility helps to run Haskell examples or to do the initial steps to port code coming from Haskell.

Still, human touch will always be required.

**Comment by ShalokShalom** [comment] 2018-01-12 13:13
No, not full Haskell. I mean Haskell in F-Sharp Plus into native F-Sharp.

**Comment by gusty** [comment] 2018-01-12 13:16
Oh, I see what you mean. I guess it makes sense, at least what we can do is to provide a brief guideline of what are the steps to take, and which decisions have to be made.

**Comment by ShalokShalom** [comment] 2018-01-12 13:45
Yes, since this seems to be a simple find-and-replace, this might be a nice project for me as a newbie. :)

**Comment by gusty** [comment] 2018-01-12 13:47
Go ahead if want to try it on your own, experiment a bit with it, then we can decide to keep it as a separate project/snippet or to include it in this lib.

**Comment by ShalokShalom** [comment] 2018-01-12 16:47
The current upload looks like we could use another file extension, in order to achieve another syntax highlight? 

I see that the table looks quite similar to here, is there a specific reason to use such one?
Is this purely to cooperate without any document editor?

**Comment by ShalokShalom** [comment] 2018-01-12 20:06
Do you consider that this is an issue in F-Sharp Formatting itself?

Well, I guess they can help, so maybe an issue there would be sane?

**Comment by gusty** [comment] 2018-01-12 20:39
> Do you consider that this is an issue in F-Sharp Formatting itself?

Yes, definitely.

> Well, I guess they can help, so maybe an issue there would be sane?

I think opened some issues there and they never came back. But please go ahead.

It seems to be working, the table is being generated but the style is missing. The tables reference a style ``header`` ``even`` and ``odd`` but they are not in .css they provide.

I'll keep looking ...

**Comment by gusty** [comment] 2018-01-12 20:44
See for example this search https://github.com/fsprojects/FSharp.Formatting/search?utf8=%E2%9C%93&q=odd&type=

They generate that style, but they don't provide it.

Alternatively if someone knows of some nice styles for these tables please include it in our template file: https://github.com/gusty/FSharpPlus/blob/master/docsrc/tools/templates/template.cshtml

**Comment by wallymathieu** [comment] 2018-01-12 21:25
that kind of styling of tables is kind of common, so they probably assume that you will bring your own

**Comment by gusty** [comment] 2018-01-12 23:49
Well, apart from that there definitely bugs in their parser, see below:
```
Generating 'D:\temp\989e43d\docsrc\tools\..\content/abstractions.html' Generating 
'D:\temp\989e43d\docsrc\tools\..\content/applicative-functors.html' Generating 
'D:\temp\989e43d\docsrc\tools\..\content/computation-expressions.html' Generating 
'D:\temp\989e43d\docsrc\tools\..\content/generic-doc.html' Generating 'D:\temp\989e43d\docsrc\tools\..\content/haskell-compatibility.html' FsiEvaluationException: Error: 
System.Exception: Unexpectedly stopped! 	[""; " |>>"; ""] 	   at 
FSharp.Markdown.Parser.parseParagraphs@756-12.Invoke(String message) in 
c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Markdown\MarkdownParser.fs:line 756
at FSharp.Markdown.Parser.parseParagraphs@673.Invoke(Unit unitVar) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Markdown\MarkdownParser.fs:line 756 	   
at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@854.Invoke(Unit unitVar0) 	   
at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) 	   
at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x) 	   
at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) 	   
at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) 	   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x) 	   
at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) 	   
at FSharp.Markdown.Parser.parseParagraphs@673.Invoke(Unit unitVar) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Markdown\MarkdownParser.fs:line 690 	   
at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@854.Invoke(Unit unitVar0) 	   
at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@854.Invoke(Unit unitVar0) 	   
at Microsoft.FSharp.Collections.SeqModule.Append@1156-1.Invoke(Unit unitVar0) 	   
at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@435.Invoke(Unit unitVar0) 	   
at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g)
```

Had to leave the table as code for now. 

If someone want to report these errors, please go ahead !

**Comment by ShalokShalom** [comment] 2018-01-13 01:35
Sounds like this is pretty much unmaintained?

Is there any alternative to FSharp Format?

**Comment by gusty** [comment] 2018-01-13 08:01
No that I know. But it's just a matter of making some noise and either they come back or eventually a new maintainer will be assigned.

Coming back to the very beginning of our conversation, I would consider now the alternative @wallymathieu proposed initially: linking to a normal .md file, embedding it, or make it open in a new window.

**Comment by ShalokShalom** [comment] 2018-01-13 08:50
And what speaks against something like this?

![screenshot_20180113_095032](https://user-images.githubusercontent.com/6344099/34904471-358a94f0-f847-11e7-85b8-1ab4c19b9b36.png)

**Comment by gusty** [comment] 2018-01-13 08:57
That looks very nice, but the problem is that it's hard to maintain.
I mean, you have to generate it each time you update it.
I had the same problem with the plantUml diagram, but finally I found a solution that generates it in the build process.
Anyway, we can also create it in plain html, right?

**Comment by wallymathieu** [comment] 2018-01-13 11:08
Indeed, plain html is simple enough 👍  so could be an alternative

**Comment by ShalokShalom** [comment] 2018-01-13 11:45
Generate it?

Its a simple screenshot. I edit the parts that I want, go fullscreen and: Screenie :D

**Comment by ShalokShalom** [comment] 2018-01-13 11:47
Does this list change so often that a difference of some seconds makes such a huge difference?

**Comment by wallymathieu** [comment] 2018-01-13 11:48
Well, you always want someone who is totally unfamiliar with things to be able to edit it

**Comment by ShalokShalom** [comment] 2018-01-13 11:51
Yeah, a spreadsheet?

**Comment by wallymathieu** [comment] 2018-01-13 13:26
So can we create an issue on formatting? We can ping forki if we are willing to help out on any fsproject stuff.

**Comment by wallymathieu** [comment] 2018-01-13 13:42
https://github.com/fsprojects/FSharp.Formatting/issues/456

**Comment by ShalokShalom** [comment] 2018-01-13 18:06
So, I think I got a great idea, while it might sound a little bit crazy first. 
Its completely optional, so you can do both. 
I just realised, that Wikipedia shows such tables in a neat way and I think its nice to link from the top page   
( [http://gusty.github.io/FSharpPlus/](http://gusty.github.io/FSharpPlus/) ) to the Wikipedia article. 
In general is Wikipedia a great place for such docs, IMHO since a lot of people will inform themself their about fsharp. So if we create a own, dedicated F-Sharp Plus page, which reflects the major aspects of the homepage can we link to it from the F-Sharp article. So, many people will get aware about the project in general and we can store the table there. Plus, such documentation in the form of examples are quite common in programming article on Wikipedia. See here: https://en.wikipedia.org/wiki/Map_(higher-order_function)

**Comment by gusty** [comment] 2018-01-13 18:10
I haven't seen a wikipedia article about a specific library, but if you wan't to try adding one, go ahead.
It might be the first :)

**Comment by ShalokShalom** [comment] 2018-01-13 18:15
Well, F-Sharp Plus is more as a library ;) 

Its a-couple-of-libraries in one 

So you can say its a library collection?

**Comment by gusty** [comment] 2018-01-13 18:20
It's true that is not a specific library, it's rather a base library, or even as @wallymathieu said, a language extension.

**Comment by ShalokShalom** [comment] 2018-01-13 18:23
Language extension sounds awesome, this is also what I thought first.

**Comment by ShalokShalom** [comment] 2018-01-14 08:01
We are also able to put it simply in Github?

https://github.com/ipfs/ipfs/blob/master/IMPLEMENTATION_STATUS.md

**Comment by gusty** [comment] 2018-01-14 08:08
Yes, that's the option discussed at the beginning, Linking to an md file.

**Comment by ShalokShalom** [comment] 2018-01-14 08:11
Apples and Lemons convinced me. I think we all should code in fruits. Also an option for applicative operators. ;)

**Comment by ShalokShalom** [comment] 2018-01-23 10:20
Do you think its sane to name this library Hashkell or H#? 😄

**Comment by gusty** [comment] 2018-01-23 10:37
No way, that's not the goal of this library.

This is meant to be a base library for F#, the fact that it uses some concepts from Haskell doesn't convert it in a Haskell emulator and that's not the purpose of this project.

Moreover, I was thinking many times in removing the Haskell compatibility and make it a separate project, but the idea of the Compatibility namespace is to have other languages.

Taking ideas from Haskell is common practice today, and you see it in most frameworks, libraries and languages.

**Comment by wallymathieu** [comment] 2018-01-23 10:39
Having it as a separate library sounds nice 👍  It also promotes the idea of F#+ base library status (if you have an eco system of libraries with distinct and sensible responsibilities).

**Comment by ShalokShalom** [comment] 2018-01-23 10:42
@gusty

>  I was thinking many times in removing the Haskell compatibility and make it a separate project, but the idea of the Compatibility namespace is to have other languages.

Is there any chance to get OCaml support in?

**Comment by gusty** [comment] 2018-01-23 10:43
True, that was also my conclusion. Actually there is in fsprojects already a [Compatibility project which has a Haskell module](https://github.com/fsprojects/FSharp.Compatibility/blob/cc701a91983fc3510e513ea7910f8f91bd31e74f/FSharp.Compatibility.Haskell/Prelude.fs) but there's almost nothing there.

That might be a good destination for the Haskell Compatibility. Feel free to open an issue to further discuss it.

@ShalokShalom regarding OCaml in that library there is some support already.

**Comment by ShalokShalom** [comment] 2018-01-23 10:44
Oh, fine ^-^

Make a list for that one too?

**Comment by voronoipotato** [comment] 2018-01-23 16:05
On the emoji for indicators I've always felt that I should be able to make emoji as operators, but F# throws up every time I try. By contrast I can use them as variables or types without issue.
```fsharp
type ``🌰`` = string
let ``🍏`` = true
let ``🍅`` = false
```

WHEN WILL THE CHAINS THAT BIND OUR OPERATORS BE LOOSED.

**Comment by ShalokShalom** [comment] 2018-01-23 18:30
This way >> https://github.com/fsharp/fslang-design :D

**Comment by ShalokShalom** [comment] 2018-01-23 18:32
Perl users will scream from feelings of jealousy and fascination

**Comment by voronoipotato** [comment] 2018-01-23 20:48
I've already tried, Don won't hear my pleas of mercy. 

https://fslang.uservoice.com/forums/245727-f-language/suggestions/5688398-allow-unicode-symbols-to-be-used-as-operators

**Comment by wallymathieu** [comment] 2018-02-04 12:17
I'm closing this issue since Haskell compatibility has been ported to FSharp.Compatibility : https://github.com/fsprojects/FSharp.Compatibility/pull/11 including the table.

**Closed by wallymathieu** 2018-02-04 12:17 UTC
